#!/usr/bin/env bash
# Made by Christian

apt-get -y update
apt install -y haproxy
sudo sed -i "$ aENABLED=1" /etc/init.d/haproxy
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 2619-web-01 35.237.188.192:80 check
    server 2619-web-02 35.172.200.11:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
