#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and print Hi in line number 9
x=0
b=10
while [ "$x" -lt "$b" ]
do
  if [ "$x" -eq "9" ]
  then
  echo "Hi"
  fi
  echo "Best School"
  x=$(( x + 1 ))
done
